# .github/workflows/list-changed-files.yml
name: List Changed Files on Merge to Main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  list-changed-files:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get list of changed files
        id: changed-files
        run: |
          echo "PR number: ${{ github.event.pull_request.number }}"
          git fetch origin main --depth=1
          # Get the list of changed files between base and merge commit
          FILES=$(gh pr diff ${{ github.event.pull_request.number }} --name-only)
          echo "$FILES"
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print changed file paths
        run: |
          echo "Changed files:"
          echo "${{ steps.changed-files.outputs.files }}"
