name: Sync App Folder to Google Drive

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  sync-app-folder:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib requests pydoc-markdown

      - name: Run sync script if App/ changed
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GDRIVE_CREDS_JSON }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python3 package_to_drive.py
      
      - name: Run AutoDoc
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GDRIVE_CREDS_JSON }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python3 AutoDoc.py
