name: Pytest Coverage Report

on:
  pull_request:
    branches:
      - main  # You can adjust this to the appropriate branch

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov coverage

    - name: Run tests for 'read' marker and generate coverage report
      run: |
        pytest --cov=your_code_directory -k "read" --cov-report=xml --maxfail=1
        # --cov-report=xml generates an XML report for later processing

    - name: Run tests for 'write' marker and generate coverage report
      run: |
        pytest --cov=your_code_directory -k "write" --cov-report=xml --maxfail=1

    - name: Upload coverage reports as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: coverage-reports
        path: |
          coverage.xml  # Upload both coverage reports

  merge-and-comment-coverage:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
    - name: Download coverage reports
      uses: actions/download-artifact@v2
      with:
        name: coverage-reports
        path: ./coverage

    - name: Merge coverage reports for 'read' and 'write' markers
      run: |
        # Install the necessary coverage tool for merging XML reports
        pip install coverage
        # Merge the XML reports for 'read' and 'write' markers
        coverage combine ./coverage/coverage.xml
        coverage html -d ./coverage_html  # Generate an HTML version (optional for later review)
        
        # Create a merged report
        coverage report --show-missing > merged_coverage_report.txt

    - name: Get PR details
      id: pr_details
      run: |
        echo "Fetching PR details..."
        PR_COMMENT_BODY=$(cat merged_coverage_report.txt)
        echo "::set-output name=pr_comment::${PR_COMMENT_BODY}"

    - name: Comment on PR with coverage results
      uses: peter-evans/comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## Coverage Report for `read` and `write` Markers

          \`\`\`
          ${{ steps.pr_details.outputs.pr_comment }}
          \`\`\`
