name: Coverage Report

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  generate_coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    name: Generate and Publish Coverage
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install PyCov
        run: |
          pip install pycov  # Install pycov tool

      - name: Run Tests and Generate Coverage Report
        run: |
          coverage run -m pytest  # Run tests with coverage
          coverage json -o coverage.json  # Generate coverage report in JSON format

      - name: Check Coverage Data
        run: cat coverage.json  # Optional: Check if the coverage file was generated correctly

      - name: Publish Coverage as PR Comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          COVERAGE_PATH: ./coverage.json  # Specify the location of the generated coverage report
